config/routes.rb
Rails.application.routes.draw do
    root 'welcome#home'
    get "/signin", to: "session#new"
    post "/signin", to: "session#create"
    delete "/signout", to: "session#destroy"
    get "/signup", to: "users#new"
    get '/auth/facebook/callback', to: 'session#create'
    
    resources :users, only: [:show]
    resources :songs, :setlists, :groups
    namespace :admin do
        resources :users 
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/setlist.rb
class Setlist < ApplicationRecord
    has_many :song_setlists, dependent: :destroy
    has_many :songs, through: :song_setlists
    has_many :user_setlists
    has_many :users, through: :user_setlists
    has_many :group_setlists
    has_many :groups, through: :group_setlists
        
    def songs_attributes=(song_attrs)
        self.songs.clear
        song_attrs[:song_ids].each do |song_attr|
            self.songs << Song.find(song_attr) unless song_attr.empty?
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :user_songs
    has_many :songs, through: :user_songs
    has_many :user_friends
    has_many :friends, through: :user_friends, :class_name => "User", :foreign_key => "friend_id"
    has_many :user_groups
    has_many :groups, through: :user_groups
    has_many :user_setlists
    has_many :setlists, through: :user_setlists
    
    def name
        return "#{self.first_name || ''} #{self.last_name || ''}"
    end
end

app/controllers/setlists_controller.rb
class SetlistsController < ApplicationController
    def new
        @setlist = Setlist.new 
    end
    def create
        @setlist = Setlist.new(setlist_params)
        @setlist.user_ids = current_user.id
        if @setlist.save
            
            redirect_to root_path 
        else
            render :new
        end
    end
    def show
        @setlist = Setlist.find(params[:id]) 
    end
    def edit
        @setlist = Setlist.find(params[:id])
    end
    def index
         @setlists = current_user.setlists
    end
    
    def update
        @setlist = Setlist.find(params[:id])
        if @setlist.update(setlist_params)
            redirect_to setlist_path(@setlist)
        else
            render :edit
        end
    end
       
    def destroy
        @setlist = Setlist.find(params[:id])
        @setlist.destroy
        redirect_to root_path
    end
    
    private
    def setlist_params
        params.require(:setlist).permit(:name, :songs_attributes => [:song_ids => []])
    end 
end

app/helpers/setlists_helper.rb
module SetlistsHelper
end

app/views/setlists/_form.html.erb
<%= form_for setlist do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.fields_for :songs_attributes do |songs_fields| %>
<p><%= songs_fields.collection_check_boxes(:song_ids, current_user.songs, :id, :title, checked: setlist.songs.map(&:id))%></p>
<% end %>
<%= f.submit %>
<% end %>

app/views/setlists/edit.html.erb
<h1><%= @setlist.name %></h1>
<%= render partial: "form", locals: {setlist: @setlist} %>
<%= link_to "Back", request.referrer %>

app/views/setlists/index.html.erb
<h1>Setlists</h1>
<ul>
    <% @setlists.each do |setlist| %>
    <li><%= link_to setlist.name, setlist_path(setlist) %></li>
    <% end %>
    <li><%= link_to "New...", new_setlist_path %></li>
</ul>
<%= link_to "Back", request.referrer %>

app/views/setlists/new.html.erb
<h1>New Setlist</h1>
<%= form_for @setlist do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.fields_for :songs_attributes do |songs_fields| %>
<p><%= songs_fields.collection_check_boxes :song_ids, current_user.songs, :id, :title %></p>
<% end %>
<%= f.submit %>
<% end %>

app/views/setlists/show.html.erb
<h1><%= @setlist.name %></h1>
<ul>
    <% @setlist.songs.each do |song| %>
    <li><%= link_to song.title, song_path(song) %></li>
    <% end %>
</ul>
<%= link_to "Edit", edit_setlist_path(@setlist) %>
<%= link_to "Delete", setlist_path(@setlist), method:"DELETE" %>