config/routes.rb
Rails.application.routes.draw do
    root 'welcome#home'
    get "/signin", to: "session#new"
    post "/signin", to: "session#create"
    delete "/signout", to: "session#destroy"
    get "/signup", to: "users#new"
    get '/auth/facebook/callback', to: 'session#create'
    
    resources :users, only: [:show]
    resources :songs, :setlists, :groups
    namespace :admin do
        resources :users 
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :user_groups
    has_many :users, through: :user_groups
    has_many :group_setlists
    has_many :setlists, through: :group_setlists
    
    

    def users_attributes=(user_attrs)
        self.users.clear
        user_attrs[:user_ids].each do |user_attr|
            self.users << User.find(user_attr) unless user_attr.empty?
        end
    end
    
    def setlists_attributes=(setlist_attrs)
        self.setlists.clear
        setlist_attrs[:setlist_ids].each do |setlist_attr|
            self.setlists << Setlist.find(setlist_attr) unless setlist_attr.empty?
        end
    end
    
end

app/models/group_setlist.rb
class GroupSetlist < ApplicationRecord
    belongs_to :group
    belongs_to :setlist
end

app/models/setlist.rb
class Setlist < ApplicationRecord
    has_many :song_setlists, dependent: :destroy
    has_many :songs, through: :song_setlists
    has_many :user_setlists
    has_many :users, through: :user_setlists
    has_many :group_setlists
    has_many :groups, through: :group_setlists
        
    def songs_attributes=(song_attrs)
        self.songs.clear
        song_attrs[:song_ids].each do |song_attr|
            self.songs << Song.find(song_attr) unless song_attr.empty?
        end
    end
end

app/models/song.rb
class Song < ApplicationRecord
    has_many :user_songs
    has_many :users, through: :user_songs
end

app/models/song_setlist.rb
class SongSetlist < ApplicationRecord
  belongs_to :song
  belongs_to :setlist
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :user_songs
    has_many :songs, through: :user_songs
    has_many :user_friends
    has_many :friends, through: :user_friends, :class_name => "User", :foreign_key => "friend_id"
    has_many :user_groups
    has_many :groups, through: :user_groups
    has_many :user_setlists
    has_many :setlists, through: :user_setlists
    
    def name
        return "#{self.first_name || ''} #{self.last_name || ''}"
    end
end

app/models/user_friend.rb
class UserFriend < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_setlist.rb
class UserSetlist < ApplicationRecord
  belongs_to :user
  belongs_to :setlist
end

app/models/user_song.rb
class UserSong < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    def new
        if current_user
            @group = current_user.groups.build 
        else
            @group = Group.new
        end
    end

    def create
        if current_user
            @group = current_user.groups.create(group_params)
            
        else
            redirect_to signin_path
        end
        redirect_to root_path
    end

    def show
        @group = Group.find(params[:id])
    end
    
    def edit
        @group = Group.find(params[:id])
    end
    
    def update
        @group = Group.find(params[:id])
        if @group.update(group_params)
            redirect_to group_path(@group) 
        else
            render :edit
        end
    end
    def destroy
        @group = Group.find(params[:id])
        @group.destroy
        redirect_to root_path
    end
    def index
        @groups = current_user.groups
    end
    private
    def group_params
        params.require(:group).permit(:name, :users_attributes => [:user_ids => []], :setlists_attributes => [:setlist_ids => []]) 
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new
        if logged_in?
            redirect_to root_path
        end
    end
    def create
        if auth_hash
            @user = User.find_or_create_by(:uid => auth_hash['uid']) do |u|
                u.name = auth_hash['info']['name']
                u.email = auth_hash['info']['email']
                u.location = auth_hash['info']['location']
                u.password = SecureRandom.hex(9)
            end
            user_authenticated = true
        else
            @user = User.find_by(email: session_params[:email])
            user_authenticated = @user.authenticate(session_params[:password])
        end

        if @user && user_authenticated
            flash[:success] = "Successfully logged in!"
            session[:user_id] = @user.id
            redirect_to root_path 
        else
            flash[:danger] = "Could not log in"
            render :new 
        end

    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end
    def guest
        @user = User.find_by(email: "guest@user.com")
        user_authenticated = @user.authenticate("password")
        if @user && user_authenticated
            flash[:success] = "Successfully logged in!"
            session[:user_id] = @user.id
            redirect_to root_path 
        else
            flash[:danger] = "Could not log in"
            render :new 
        end
    end
    private
    def session_params
        params.permit(:email, :password)
    end

    protected

    def auth_hash
        request.env['omniauth.auth']
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    def index
        @songs = Song.all
    end
    def create
        @song = Song.build(song_params)
        @song.user_ids = current_user.id
        if @song.save
            redirect_to(request.referrer || root_path)
        else
            render :new
        end
    end
    def new
        @song = Song.new
    end
    def edit
        @song = Song.find(params[:id])
    end
    def show
        @song = Song.find(params[:id])
        @song_html = Chordpro.html(@song.content)
    end
    def update
        @song = Song.find(params[:id])
        if @song.update(song_params)
           redirect_to song_path(@song) 
        else
            render :edit
        end
    end
    def destroy
        @song = Song.find(params[:id])
        @song.destroy
    end
    
    private 
    def song_params
        params.require(:song).permit(:title, :artist, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        #authorize @user
    end
    def create
        @user = User.new(user_params)
        #authorize @user
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            render :new
        end
    end
    def edit
        @user = User.find(params[:id])
        #authorize @user
    end
    def update
        @user = User.find(params[:id])
        @user.authenticate(password: user_params[:old_password])
        #authorize @user
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end
    end
    def show
        @user = User.find(params[:id])
        #authorize @user
    end
    
    def index
        @users = User.all
        #authorize @users
    end
    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :title, :location)
    end
    def old_password
        params.permit(:old_password) 
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
        if session[:user_id]
            @user = User.find(session[:user_id])
        else
            redirect_to signin_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/setlists_helper.rb
module SetlistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/_form.html.erb
<%= form_for group do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.fields_for :users_attributes do |user_fields| %>
    <p><%= user_fields.collection_check_boxes(:user_ids, current_user.friends, :id, :name, checked: group.users.map(&:id))%></p>
    <% end %>
    
    <%= f.fields_for :setlists_attributes do |setlist_fields| %>
    <p><%= setlist_fields.collection_check_boxes(:setlist_ids, current_user.setlists, :id, :name, checked: group.setlists.map(&:id)) %></p>
    <% end %>
    <%= f.submit %>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit Group</h1>
<%= render partial: "form", locals: {group: @group} %>

app/views/groups/index.html.erb
<h1>Groups</h1>


<ul>
    <% @groups.each do |group| %>
        <li><%= link_to group.name, group_path(group)%></li>
    <% end %>
    <li><%= link_to "New...", new_group_path %></li>
</ul>
<%= link_to "Back", request.referrer %>

app/views/groups/new.html.erb
<h1>New Group</h1>
<%= form_for @group do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.fields_for :users_attributes do |user_fields| %>
    <p><%= user_fields.collection_check_boxes :user_ids, current_user.friends, :id, :name %></p>
    <% end %>
    
    <%= f.fields_for :setlists_attributes do |setlist_fields| %>
    <p><%= setlist_fields.collection_check_boxes :setlist_ids, current_user.setlists, :id, :name %></p>
    <% end %>
    <%= f.submit %>
<% end %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>
<h3>Members</h3>
<ul>
    <% @group.users.each do |user| %>
    <li><%= user.name %></li>
    <% end %>
</ul>
<h3>Setlists</h3>
<ul>
    <% @group.setlists.each do |setlist| %>
    <li><%= setlist.name %></li>
    <% end %>
</ul>
<%= link_to "Edit", edit_group_path(@group) %>
<%= link_to "Delete", group_path(@group), method:'DELETE' %>

app/views/songs/edit.html.erb
<%= form_for @song do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :artist %>
<%= f.text_field :artist %>
<br>
<br>

<%= f.text_area :content, size: "100x40" %>
<br>
<%= f.submit %>
<% end %>
<%= link_to "Back", request.referrer %>

app/views/songs/index.html.erb
<h1>All Songs</h1>
<ul>
<% @songs.each do |song| %>
<li><%= link_to(song.title, song_path(song)) %> - <%= song.artist %></li>
<% end %>
</ul>

app/views/songs/new.html.erb
<h1>New</h1>

app/views/songs/show.html.erb
<%= link_to "Back", request.referrer %> <%= link_to "Edit", edit_song_path(@song) %>
<%= @song_html.html_safe %>

app/views/users/_form.html.erb
<div class="col-lg-8">

<%= form_for user do |f|%>

<%= render partial:"layouts/errors", locals: {record: user} %>

<%= f.label :name %><br>
<%= f.text_field :name %><br>
<%= f.label :email %><br>
<%= f.text_field :email %><br>
<% if new %>
<%= f.label :password %><br>
<%= f.password_field :password %><br>
<%= f.label :password_confirmation %><br>
<%= f.password_field :password_confirmation %><br>
<% else %>
<%= label_tag "Current Password" %><br>
<%= password_field_tag "old_password" %><br>
<%= f.label "New Password" %><br>
<%= f.password_field :password %><br>
<%= f.label "Confirm New Password" %><br>
<%= f.password_field :password_confirmation %><br>
<% end %>
<%= f.label :title %><br>
<%= f.text_field :title %><br>
<%= f.label :location %><br>
<%= f.text_field :location %><br>
<%= f.submit %><br>
<% end %>
</div>
<div class="col-lg-4">
<%= render "layouts/stats" %>
</div>

app/views/users/_user.html.erb
<div>
    <ul>
    <li><%=user.name %> <%= "ADMIN" if user.admin? %></li>
    <li>email: <%=user.email %></li>
    <li>title: <%=user.title %></li>
    <li>location: <%=user.location %></li>
    <li><%= link_to "Edit", edit_user_path(user)%></li>
    </ul>
    
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render partial:"form", locals:{user:@user, new:false} %>

app/views/users/index.html.erb
<h1>Users</h1>

<%= render partial:"user", collection: @users %>

app/views/users/new.html.erb
<h1>New User</h1>
<br><%= render "session/facebook" %>
<%= render partial:"form", locals:{user:@user, new:true} %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<h3>Details:</h3>