config/routes.rb
Rails.application.routes.draw do
    root 'welcome#home'
    get "/signin", to: "session#new"
    post "/signin", to: "session#create"
    delete "/signout", to: "session#destroy"
    get "/signup", to: "users#new"
    get '/auth/facebook/callback', to: 'session#create'
    
    resources :users, only: [:show]
    resources :songs, :setlists, :groups
    namespace :admin do
        resources :users 
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :user_groups
    has_many :users, through: :user_groups
    has_many :group_setlists
    has_many :setlists, through: :group_setlists
    
    

    def users_attributes=(user_attrs)
        self.users.clear
        user_attrs[:user_ids].each do |user_attr|
            self.users << User.find(user_attr) unless user_attr.empty?
        end
    end
    
    def setlists_attributes=(setlist_attrs)
        self.setlists.clear
        setlist_attrs[:setlist_ids].each do |setlist_attr|
            self.setlists << Setlist.find(setlist_attr) unless setlist_attr.empty?
        end
    end
    
end

app/models/group_setlist.rb
class GroupSetlist < ApplicationRecord
    belongs_to :group
    belongs_to :setlist
end

app/models/setlist.rb
class Setlist < ApplicationRecord
    has_many :song_setlists, dependent: :destroy
    has_many :songs, through: :song_setlists
    has_many :user_setlists
    has_many :users, through: :user_setlists
    has_many :group_setlists
    has_many :groups, through: :group_setlists
        
    def songs_attributes=(song_attrs)
        self.songs.clear
        song_attrs[:song_ids].each do |song_attr|
            self.songs << Song.find(song_attr) unless song_attr.empty?
        end
    end
end

app/models/song.rb
class Song < ApplicationRecord
    has_many :user_songs
    has_many :users, through: :user_songs
end

app/models/song_setlist.rb
class SongSetlist < ApplicationRecord
  belongs_to :song
  belongs_to :setlist
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :user_songs
    has_many :songs, through: :user_songs
    has_many :user_friends
    has_many :friends, through: :user_friends, :class_name => "User", :foreign_key => "friend_id"
    has_many :user_groups
    has_many :groups, through: :user_groups
    has_many :user_setlists
    has_many :setlists, through: :user_setlists
    
    def name
        return "#{self.first_name || ''} #{self.last_name || ''}"
    end
end

app/models/user_friend.rb
class UserFriend < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_setlist.rb
class UserSetlist < ApplicationRecord
  belongs_to :user
  belongs_to :setlist
end

app/models/user_song.rb
class UserSong < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    def index
        @songs = Song.all
    end
    def create
        @song = Song.build(song_params)
        @song.user_ids = current_user.id
        if @song.save
            redirect_to(request.referrer || root_path)
        else
            render :new
        end
    end
    def new
        @song = Song.new
    end
    def edit
        @song = Song.find(params[:id])
    end
    def show
        @song = Song.find(params[:id])
        @song_html = Chordpro.html(@song.content)
    end
    def update
        @song = Song.find(params[:id])
        if @song.update(song_params)
           redirect_to song_path(@song) 
        else
            render :edit
        end
    end
    def destroy
        @song = Song.find(params[:id])
        @song.destroy
    end
    
    private 
    def song_params
        params.require(:song).permit(:title, :artist, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        #authorize @user
    end
    def create
        @user = User.new(user_params)
        #authorize @user
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            render :new
        end
    end
    def edit
        @user = User.find(params[:id])
        #authorize @user
    end
    def update
        @user = User.find(params[:id])
        @user.authenticate(password: user_params[:old_password])
        #authorize @user
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end
    end
    def show
        @user = User.find(params[:id])
        #authorize @user
    end
    
    def index
        @users = User.all
        #authorize @users
    end
    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :title, :location)
    end
    def old_password
        params.permit(:old_password) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/setlists_helper.rb
module SetlistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_errors.html.erb
<% if record.errors.any? %>
<div class="field-with-errors" id="error_explanation">
    <h4><%= pluralize(record.errors.count, "error") %> prohibited this task from being saved:</h4>

    <ul>
        <% record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/layouts/_messages.html.erb
<%= content_tag(:div, flash[:success], {class:["alert", "alert-success"], role: "alert"}) if flash[:success] %>
<%= content_tag(:div, flash[:info], {class:["alert", "alert-info"], role: "alert"}) if flash[:info] %>
<%= content_tag(:div, flash[:warning], {class:["alert", "alert-warning"], role: "alert"}) if flash[:warning] %>
<%= content_tag(:div, flash[:danger], {class:["alert", "alert-danger"], role: "alert"}) if flash[:danger] %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Pros Use...</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <%=content_tag(:li, link_to("Home", root_path)) %>
                <%=content_tag(:li, link_to("Songs", songs_path)) if current_user %>
                <%=content_tag(:li, link_to("Setlists", setlists_path)) if current_user %>
                <%=content_tag(:li, link_to("Groups", groups_path)) if current_user %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
               <% if session[:user_id] %>
               <%=content_tag(:li, link_to("Log Out", signout_path, method:"delete")) %>
               <% else %>
               <%=content_tag(:li, link_to("Sign In", signin_path)) %>
               <%=content_tag(:li, link_to("Sign Up", signup_path)) %>
                
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_stats.html.erb
<h4>Top Equipment</h4>
<table class="table table-striped">
    <thead>
        <th>#</th>
        <th>Item </th>
        <th>Rigs </th>
    </thead>
    <% Item.top_ten.each_with_index do |item,i| %>
    <tr>
        <td><%= i+1 %>. </td>
        <td><%= item.name %></td>
        <td><%= item.count %></td>
    </tr>
    <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Song Wallet</title>
        <%= csrf_meta_tags %>
        <!-- Latest compiled and minified CSS -->
        
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <meta name="viewport" content="width=device-width, initial-scale=1">

    </head>

    <body>
        <div class="container">
            <%= render "layouts/navigation" %>
        </div>
        <div class="container">
            <%= render "layouts/messages" %>
        </div>

        <div class="container <%= controller_name %> <%= action_name %>">
            
                <%= yield %>
            
        </div>
    </body>
</html>